# Generated by Django 5.1.1 on 2024-12-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublisherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='timing',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='tutor',
            name='timing',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=100),
        ),
    ]
